apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-nginx-web
  labels:
    app: nginx-server
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: nginx-server
  template: 
    metadata:
      labels:
        app: nginx-server
    spec: 
      containers:
        - name: web
          image: nginx
          ports:  
            - name: web
              containerPort: 80
              protocol: TCP
